# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_goal_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='milestone',
        ),
        migrations.AddField(
            model_name='target',
            name='milestone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='targets.Milestone'),
        ),
    ]
