# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0004_auto_20160629_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
