# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0004_auto_20160629_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_completed_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_targets', through='targets.TargetAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
