# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_target_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_targets', to=settings.AUTH_USER_MODEL),
        ),
    ]
