language: python
python:
- '3.5'
addons:
  code_climate:
    repo_token: c711107a821fc3b78db7028995deb601bb43af70473c6349bada5f8fe27bda0a
script: coverage run --branch --omit=*test*,*migrations* --source=projects manage.py
  test
after_script:
- codeclimate-test-reporter
deploy:
  provider: heroku
  app:
    master: orbital2016
    deployment-test: orbital2016-dev
  run: python manage.py migrate
  api_key:
    secure: "J3uBPZU+rm+rrnEWZUm41ZxlsQi7PHLJrqCy2B7NhSa/OOT5yKxNC+2PgPIq3CYx4IBrHQJAc7tRprDqvE7Twm8/q1BlT2fLXghVwGgFQsWuopMkQT4Hx3/TLhBE252T0HjdKw3a4eMxJna0kl9Tk1Xo7BxidZk8FIBHCPEYwr7hvZF8z+rd7qg1NvAZroaiggdnXEwnRv9dnuELYWr0aNqwgANZdErfhAcsRG1Vrlidr/Xb37fpHtpPojC0QedGBwIKhRaNKh8rOeQop4IhmnQpcUlDFlzJ7B1DgWkoGI4RBTJEUKsZhJoVjx6YCaeU3P67G8stRFmrDdNIE75ZEqQGkzkKCq5U5B3XW2lmeP2izz1Nd3kUQeSoxL8JyAgiTVRNIiIm4U2ARsZB73qOSV7wMZbetQuGULhtFJe//1kZgpeCy6kKuHwyrEL3EoRdWEMXqNXjkYMaHK9Nu7NrJsyCTdzi4LAa12t9Bp3cHXLgGQbhC+BYM65GOgTSsiENLnmFM5b5PHJ8FPrg8ATcD3CFECe/o2Tndd4MYhzU6VwFAgHc93cN4xOKAsRkOw/zjmHVay0G4AcwrozetLHdHUwQWrmISg/jIxIy+XcdrtBPFigBcPaSAa4c2BQ8yM7AaTPF9VBMdK84LUyu41y6tdVaV17ToJLKh5Z+cK5pc6U="
