language: python
python:
- '3.5'
addons:
  code_climate:
    repo_token: c711107a821fc3b78db7028995deb601bb43af70473c6349bada5f8fe27bda0a
script: coverage run --branch --omit=*test*,*migrations* --source=projects manage.py
  test
after_script:
- codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: YujeVG+kHM5LjAwdBlHP0VvXTd2JvPHkRj+0R2y9a/K5wykxmFE01nAC5Q/TpjzgKoUeIHIC2/2bJ+NzH8QO7JU98jJfDWlIfTPViSBnmRBzMaqwBVYPh3WKLxFW/ZX9XFC36rx1g7SvBqgs/op8jeV/VInF6fpmWRKNgQbQ00PP3SVyfTN76tck23HWWVSjQ870XDREsAZkM6CtAqckbdXxyBA/UCn7h56/bDdUyKs6pAdEoXzyzfi7MMhy0c4qbc/jgd+OqosXla6kGyc0GXbljG71cOvor0LxuS6E2jjbCUXq3uzn1jby6ubClJz6a4d2yKxi3ePRwIdLIaduPJWVuEAqldY02XDv0HJdEeIFhf8eCHZwQZtT5AMChzt5clSpSG/N9J4PuvLRjwCLlRHDDQBntpbLAxDS1vnmf/GQDB8lKwZp2SC4RYJ2cCdF8NIsbb6hXiZbGBj1OVsJRbLCm2+wqmFhfU+3ufNfp6nnQyfY3rEDdpkSrlPId5TUdQPrT2CfqnBwzCI0yNJMxxnx9+HwmuJBrABPpFcC812XRqJKCQxtF2gfh08/9sWns4rZJ6A1HRZyfZbwIklfnH87E/Of1XDtNirdabswjzVolZpjUhM9Qnc9ge+WEUUrH6d9vdA8YUUWCXhjCeP+DZm/9W+eW9WgublG3ahUgas=
  app:
    master: orbital2016
    deployment-test: orbital2016-dev
  run: python manage.py migrate
