language: python
python:
  - "3.5"
addons:
  code_climate:
    repo_token: c711107a821fc3b78db7028995deb601bb43af70473c6349bada5f8fe27bda0a
script: coverage run --branch --omit=*test*,*migrations* --source=projects src/manage.py test
after_script:
  - codeclimate-test-reporter